apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-poc
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: pockubernetes.azurecr.io/nodejs-final1:v1.0
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-poc
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
